### ISSUE TITLE
【Middle】カレンダー表示の調整

### ISSUE THREAD

**Issue by KU-onji** [KU-onji/ene_backend#11]
以下のやつをやりたい
- 今日のボックスを何らかの色で塗る
- 土曜の日付を青、日曜の日付を赤で表示
- 今月以外の日付を灰色にする

やや細かいけど一気にカレンダーっぽくなる気がする

**Comment by katakahas** [comment]
#17 で解決されました

**Comment by KU-onji** [comment]
カレンダー表示は完了。
あとでタスクの表示をやる。
